version: '3.6'

# networks:
#   ollama:

services:
  # ollama:
  #   image: ollama/ollama:latest
  #   build: 
  #     context: ./
  #     dockerfile: ./ollama/Dockerfile     
  #   networks:
  #     - ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [ gpu ]
  #   volumes:
  #     - ./data/ollama:/root/.ollama
  #   ports:
  #     - 11434:11434

  multi_device_ai_agent:
    image: johncapobianco/multi_device_ai_agent:multi_device_ai_agent
    container_name: multi_device_ai_agent
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile   
    ports:
      - "8501:8501"
    # depends_on:
    #   - ollama
    # networks:
    #   - ollama
    # environment:
    #   - OLLAMA_URL=http://ollama:11434      